### ISSUE TITLE
Stereo samples are half as loud as they should be

### ISSUE THREAD

**Issue by strongholdmedia** [schismtracker/schismtracker#118]
I know that there is no possibility for comparison, since IT did not support stereo samples, but to me, it seems that when I save the same sample separated as left and right channels, then load them at 100% volume (that is, 0x40 / 64 decimal), panned hard left / hard right, they are twice as loud as if I load the stereo wav and use it as a stereo instrument.

I basically think that if I still have to double the sample to get the desired volume, there is no real use of having stereo support.

**Comment by jangler** [comment]
I think that's an unusual perspective. In any case I don't see a way to "fix" this in a way that preserves compatibility with previous versions of Schism Tracker and other players that support stereo samples. For all intents and purposes, this is just how stereo samples work in the IT format.

**Comment by strongholdmedia** [comment]
It may still worth considering adding a switch or something like that, since this way, the only way to "fix" the issue is halving all other (non-stereo) samples global volume, hereby reducing the already not-too-wide scale of possible volume levels to 32..
..okay, I know that this is not a professional DAW or whatever but still.

**Comment by sagamusix** [comment]
Note: The technical explanation for this is that Schism Tracker, like most other trackers, uses linear pan law. If you play two samples panned left and right, they are twice as loud as just playing one centered sample - no matter if that sample is stereo or not. I'm not sure what kind of "switch" could be added here.

**Comment by strongholdmedia** [comment]
What you write sounds logical but is in fact not.
Technically speaking, a stereo sample is by nature two samples, one hard left and one hard right.
Technically, there is no such thing as "centered stereo sample"; it is an oxymoron.
For stereo samples, you have no pan, just balance (at most).

**Comment by sagamusix** [comment]
I simply explained what is *technically* happening in the engine. The behaviour your observe is a direct consequence of this implementation. Your explanation is an alternative way of implementing sample panning (closer to how it's e.g. done in SF2 soundfonts which do not have native stereo samples), but it's not what Schism Tracker or other trackers are doing.

> Technically, there is no such thing as "centered stereo sample"; it is an oxymoron.

Since you can pan stereo samples freely, it's not an oxymoron. With Schism Tracker's pan law, a centered stereo sample is simply played with identical volume levels for the left and right channels, and panning it to the left or right changes the volume levels of the two channels individually. There are also other ways to pan stereo samples.
