### ISSUE TITLE
DEADLOCK.XM playback issues?

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#148]
As mentioned in #145. Of course, XM playback is **not** supported by Schism, but if there's a bug in the import logic then it should be fixed.

**Comment by sagamusix** [comment]
If this is only about the short bleeps heard in patterns 30/31 (which always existed), then this issue cannot really be fixed: In XM, an instrument number with no note next to it resets a couple of instrument properties of the currently playing note (if there is one), and memorizes the new instrument for the next instrument-less note. IT has explicit sample swapping, so it does not just reset some instrument properties, but also instantly triggers the new the instrument rather than just memorizing it for the next note. There is no sane way to "fix" this during import, it would require a lot of book-keeping and would still not guaranteed to be perfect.

**Comment by jangler** [comment]
Never mind then; I didn't realize that the sample swapping was the issue. Agreed and closing.
