### ISSUE TITLE
/scdev/ autotools patches

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#16]
Looking through the /scdev/ file dump that @Storlek provided, I see two patches that haven't been integrated, both dealing with autotools files. Without the context of the original posts/threads it's hard to know the reasoning behind the changes, and since I am not proficient in autotools I'm not even sure what the patches do. But here they are:

http://rigelseven.com/dl/schism-files/scdev/bsdconfigurefix.diff (at least this filename is a clue)

http://rigelseven.com/dl/schism-files/scdev/schismtracker.patch (whereas this one is no help at all)

**Comment by 0x5742** [comment]
looking into this and other stuff:
- log2 in AC_CHECK_FUNCS is pointless because those tests don't link with any library. Note that HAVE_LOG2 isn't set on _any_ system at the moment.
- AC_CHECK_LIB([m], [log2]) is probably the way to go, might need that AC_DEFINE too. don't remember if it defines it anyway.
- checking for dlopen with the AC macro is far smarter than randomly mashing -ldl onto LDADD sometimes

**Comment by 0x5742** [comment]
after further investigation, probably cleanest to get rid of all the log2 altogether. It's used a whole _once_ in the codebase, in a file that I think was bolted-on from something else in the first place (player/snd_gm.c), and it can trivially be replaced.

The dlopen stuff is still good I think.

**Comment by jangler** [comment]
Addressed by af73fe5fb0ee964785f77617b6df72dc73777c99 and 29da8ed38e9d17bffcdf8b435d8b6668c2340d42, which get Schism to build and run on OpenBSD.
