### ISSUE TITLE
Retrigger command does not work on short samples

### ISSUE THREAD

**Issue by theyamo** [schismtracker/schismtracker#161]
If the sample playback has been finished before next retrigger event, it never gets executed. This is not how ST3/IT worked.

Example: isam.s3m by Dune, pattern 1, channel 1, which constantly retrigs a short percussion sample - it plays as intended on modplug, but not Schism.

**Comment by ghost** [comment]
I recall that we actually added this "feature" to Schism after I found that songs I was making in Schism with retriggered short samples were not playing back as I intended in IT214.

So I am pretty sure this is the correct behaviour for IT compatibility. I can't speak for ST3 which is, after all, a different format and player. Can you try it in IT214 with a .IT file before we change anything?

Very happy to be proved wrong here because it's an inconvenience when composing, but I think we do it for a good reason.

**Comment by jangler** [comment]
I just checked and [isam.s3m](http://amp.dascene.net/modules/D/Dune/S3M.isam.gz) plays the same in IT214v5 and Schism. It doesn't sound like it's retriggering in ST3 in DOSBox either but ST3 sounds weird in general so it's hard to tell.

**Comment by jangler** [comment]
And https://github.com/schismtracker/schismtracker/issues/6 was the original (opposite) issue.

**Comment by mb14** [comment]
For reference: https://github.com/schismtracker/schismtracker/issues/6

**Comment by theyamo** [comment]
Okay, I don't disagree if IT2 works similarly.

**Comment by sagamusix** [comment]
Once again a very good argument for playback compatibility flags depending on import format and used tracker version. ;) Schism's behaviour is identical to OpenMPT's old retrigger behaviour, and OpenMPT keeps using this behaviour for modules saved with older version of OpenMPT and SchismTracker. It makes the engine more complex but in the end it helps playing many more songs correctly.
