### ISSUE TITLE
OSX - screen scaling corrupts colors

### ISSUE THREAD

**Issue by dariusk** [schismtracker/schismtracker#168]
When I attempt to scale Schism Tracker or go into full screen mode, the colors end up with a blue wash over them, like so:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/266454/42671993-0ff0228c-8618-11e8-9b32-f790810da6d5.png">

This is the case in the current development branch when I build from source, but I've seen this problem going back to builds from 2017 or even earlier. Is there a workaround for this?

**Comment by jangler** [comment]
Ah, the Adlib Tracker II color scheme:

![at2_screenshot](https://user-images.githubusercontent.com/1653421/42701315-42c7a03c-8694-11e8-8594-247eddc4dc83.png)

No idea what this is. Have you tried the different video drivers on the System Configuration (Ctrl-F1) screen?

**Comment by dariusk** [comment]
That fixed it, thank you! I didn't even know there was a System Config menu.

**Comment by jangler** [comment]
For future reference, what video mode worked for you?

**Comment by dariusk** [comment]
YUV Video Overlay

**Comment by asbjornu** [comment]
Is it possible to set `YUV Video Overlay` as the default for macOS somehow?

**Comment by asbjornu** [comment]
Also, `YUV Video Overlay` doesn't scale as nice as `SDL Video Surface`. The former looks nice in a matching aspect ratio, but if you stretch beyond the aspect ratio in any direction, it starts looking distorted. I guess this is because `YUV` seemingly doesn't do font anti-aliasing? `OpenGL Graphics Context` has the same problem. Either way, it would be nice to get `SDL Video Surface` to work on macOS (again).
