### ISSUE TITLE
File/Folder  browser automatically reads larger files - perhaps could be lazier

### ISSUE THREAD

**Issue by zeffii** [schismtracker/schismtracker#17]
Maybe it's just my machine but when navigating into directories that have larger .wav files, ST tends to want to read all of them even if i'm trying to navigate into another folder of samples. Could the File/Folder browser check just file-size instead and if the file is above X mb then load it for waveform viewing/playback only if the caret/selection falls on that file.

I know in the meantime to avoid directories with large files, but eventually maybe this can be considered.

**Comment by jangler** [comment]
Yeah, this is platform-specific. On POSIX systems, you can `mmap()` the file. On Windows, the code does something similar with `CreateFileMapping()` and `MapViewOfFile()`. The fallback behavior is to read the whole file, which is super slow and problematic if I force that behavior.

I'm not sure why Windows memory mapping would be drastically slower than Linux memory mapping, though.

**Comment by 0x5742** [comment]
Is the log (Ctrl-F11) showing any issues related to CreateFileMapping or MapViewOfFile?

**Comment by zeffii** [comment]
```
MapViewOfFile failed with 8
some_file_name.zip: Not enough space
```

this zip happens to be quite big :)

**Comment by 0x5742** [comment]
what the heck is 8?!

**Comment by 0x5742** [comment]
okay, [8 is ERROR_NOT_ENOUGH_MEMORY](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382%28v=vs.85%29.aspx), but that shouldn't be a thing. seems it's somehow still sucking in the whole file for whatever reason

**Comment by 0x5742** [comment]
zeffii: is it hanging the program or otherwise breaking things, or just spitting out some log noise?

If the program is otherwise usable then it's basically working as intended, likely the file is literally too big to load with a 32-bit program in the first place (and I think the existing Schism Tracker binaries are all 32-bit compiled)

**Comment by 0x5742** [comment]
I revamped the Windows file loading code a bit. Shouldn't change anything, but it at least clarifies the error messages.

**Comment by zeffii** [comment]
The zip in that directory was about 3.2 gb. ST doesn't crash just chokes 5 or 10 seconds when inspecting directories with large files, eventually it's usable again. No related log messages beyond the one I pasted already.

I don't want to distract you from more important things, avoiding these directories is easy.

Thanks for rebooting this tracker :)

**Comment by 0x5742** [comment]
okay, 20 questions time :)

What is your OS version?

Do you know if you're using an NTFS or FAT partition?

Is this on a local drive or a network share?

**Comment by zeffii** [comment]
crappy lenovo ideapad 100 14IBY (2gb ram)
win10 - 64bit, local drive, NTFS  450gb total, 350gb free.

**Comment by 0x5742** [comment]
Well, the only tangible differences from your setup to mine are that I have a heck of a lot more RAM, and I'm on 2008R2, not Win10. I have no idea what the issue might be.

**Comment by alugarius** [comment]
@zeffii I think its your 2GB RAM, get at least 4 or 8gb
Its waaay to small for win10
windows 10 eats 2GB only while updating.

**Comment by ghost** [comment]
Was the zip file support removed? current schismtracker cannot read .zip files (F9), or am I doing it wrong?

**Comment by sagamusix** [comment]
Can't reproduce this with the latest version either. @zeffii can you check if this still is an issue for you?

> Was the zip file support removed? current schismtracker cannot read .zip files (F9), or am I doing it wrong?

SchismTracker never supported ZIP files. But since SchismTracker first needs to look at the file contents to see if it can load the file, the file needs to be mapped to memory first, and if that fails, the whole file would be read from disk - which appears to have been the case here.

**Comment by mrpapersonic** [comment]
This should only happen on 32-bit where the address space is too small to fit large files (about 2GB max in the allocation pool is given to the application)

This can also happen under POSIX systems with mmap() where it sets errno to ENOMEM.

In any case, if MapViewOfFile()/mmap() fails with a not enough memory error then slurp ought to not even attempt to load the *entire file*... and on win32 it already *does* do that

**Comment by mrpapersonic** [comment]
slurp supports stdio streams now so large files should work well.

This error was probably an issue with the address space. 32-bit windows applications only support up to 2 GiB of address space without adding a special flag in the linking process which IIRC is for programs that are stupid and use INT_PTR assuming that its always positive.

In any case the stuff treating a CreateFileMapping or MapViewOfFile error as unrecoverable has also been changed because of an unrelated issue (in windows 9x those functions are stubs that always error)
