### ISSUE TITLE
Volume envelope for instrument does not get switched ON by its setting

### ISSUE THREAD

**Issue by strongholdmedia** [schismtracker/schismtracker#177]
I guess `Some more obscure instrument-list functions are still unimplemented or half-implemented` in TODO readme refers to this.

The thing is, support is there, so that if I load a module with this setting, it plays great. It is just that I cannot toggle this from the UI.

E.g. if I draw an envelope, it is ignored. Even when turned ON.
If I set the point 0 volume to 0, the sample is still played with full volume.

**Comment by jangler** [comment]
I can't reproduce this; you mean that you can't create (working) volume envelopes at all?

**Comment by strongholdmedia** [comment]
Yes, absolutely.
At least when working with new modules.
(I also started experiencing strange issues like multiple instrument "tabs" are set to "active" at the same time.)
They look "very nice", but the cursor is not starting on them when the instruments are played.
**EDIT**: checked; when importing sample into a module made (some 22years ago) in IT, and creating instrument in it, then envelope works flawlessly for the new instrument as well.

**Comment by jangler** [comment]
Yeah, I opened an issue for the tabs when I checked this a couple of hours ago: https://github.com/schismtracker/schismtracker/issues/178

Mouse support in Schism is sketchy because I expect the main devs (and myself) used the keyboard for almost everything. But I did this with version 20180108:

1. Opened Schism Tracker.
2. Loaded a sample.
3. Used the mouse to set the Control to Instruments on the F12 screen.
4. Used the mouse to select the Volume tab on the F4 screen.
5. Used the mouse to create and move a few nodes in the volume envelope.

Volume Envelope on that tab was set to On as soon as I started manipulating the envelope, and it works correctly when I place a note in a pattern using that instrument.

**Comment by strongholdmedia** [comment]
How can I find out the version? :)
Mine shows "built Aug 14 2018 12:39:18" but I am unsure if this corresponds to a tag.
(As a side note, I do not find a revision tagged "20180108" neither.)

**Comment by strongholdmedia** [comment]
Um, this is very irregular.
I found out I am running 20180810.
I tried to create a module now and this works for me too.
BUT when I load the module I had the problem with (created like two months ago with the version then available in Debian repository, presumably 20180513) and load a sample, **of course** that envelopes didn't work, since there were actually **no** instruments - "control" was on "samples".
Turns out that sample mode *is* the default, but when you create a new module *after* loading one that did use instrument mode, *this is not reset*.
Please decide whether making instrument mode the default or resetting this on new module (when e.g. samples are set to be cleared) is better (or even leaving it as is but documenting this quirk).
_(I think the first one makes more sense, but the second is better in terms of compatibility.)_

**Comment by strongholdmedia** [comment]
Another problem is that when I turn on instrument mode, and answer "yes" to the question "Initialize instruments?", actual instruments are _only created for mono samples_.
There seems no easy way to create an instrument for a stereo sample that has already been loaded into "sample control mode".
I try to fill the table manually now and report whether it works or not.

**Comment by jangler** [comment]
That's funny, because the only sample I tested with was a stereo sample. And yeah… initializing a new module is not as clean as it should be. That's a bug by itself IMO.

**Comment by jangler** [comment]
And yeah, you're right, there's no 20180108 tag. I don't know why mine is 20180108… I don't even really remember how the autotools thing that sets up the version number works.

**Comment by jangler** [comment]
I actually disagree about "New Song", now that I look at it – the dialog only implies that samples etc will be deleted as indicated, not that *everything* will be reset. If you're in instrument mode, Schism even shows a dialog asking whether you want to create a host instrument whenever you load a sample. Not sure it's worth documenting since it's IT behavior and people generally defer reading documentation until it's too late.

Since I can't reproduce the stereo instrument issue, I'm going to close this for now. If you have more info on a specific case where it fails, definitely mention it, but the sequence of `1. start Schism 2. load stereo sample 3. change to instrument mode and say yes to prompt` works fine for me.

**Comment by strongholdmedia** [comment]
Okay, I will see if the problem still exists, and get back with anything.

**Comment by strongholdmedia** [comment]
It seems that the envelope issue is non-existent in today's master.
It also seems that instrument is properly created for stereo samples added before initializing instruments (i.e. in sample mode).
So everything should be resolved.
