### ISSUE TITLE
Wii port seems to be lost.

### ISSUE THREAD

**Issue by bandithedoge** [schismtracker/schismtracker#179]
The download link on the Wiibrew page is dead. Where can I find the port?

**Comment by jangler** [comment]
Don't know; the last Wii port was from 2011, contributed by Storlek, and was listed on the former schismtracker.org as "no longer supported".

**Comment by teimoso** [comment]
The download link for the 2011-01-01 build has been archived by archive.org's Wayback Machine:
https://web.archive.org/web/20110817111514/http://schismtracker.org/dl/schismtracker-20110101-wii.zip
The Wiibrew page also claims that it's downloadable through the Homebrew Browser, so that might still work if it doesn't use the same URL.

I'm unable to find the source code, unfortunately.

**Comment by bandithedoge** [comment]
Thanks. Unfortunately, HBB doesn't work on my Wii. I heard other people had problems as well so I guess the servers are down.

**Comment by bandithedoge** [comment]
I tried the link provided by @teimoso and it crashes on startup.

**Comment by teimoso** [comment]
I don't have easy access to a Wii at the moment, but I couldn't get it to work in Dolphin either. I _was_ able to run the Homebrew Browser in Dolphin, but downloading Schism Tracker failed at around 0.8MB (Creating folders failed). The whole thing was in a half-broken state, so it's most likely my (or the emulator's) fault. 

I was able to start the download without it, but [WiiBrew's page for the Homebrew Browser](http://www.wiibrew.org/wiki/Homebrew_Browser) mentions that in `settings.xml` there is a "`settings-server`" option that uses different servers when set to 1 (instead of the default 0). Have you tried that?

**Comment by bandithedoge** [comment]
I have tried the setting, but the app just gives me errors on startup.

**Comment by mrpapersonic** [comment]
[Here](https://github.com/schismtracker/schismtracker/files/8403347/schismtracker-20100202-wii.zip) is an older version that works fine on my Wii.

**Comment by mrpapersonic** [comment]
I got the Wii port building and a binary is included with the latest release.

**Comment by vcaputo** [comment]
> I got the Wii port building and a binary is included with the latest release.

Nice!  but how do we test such a thing?

**Comment by mrpapersonic** [comment]
I tested it with my own wii for the past couple of days, it works fine for as much as i've done. I had to make a couple of changes to devkitpro's SDL2 branch to get USB keyboards working and opened a PR [here](https://github.com/devkitPro/SDL/pull/68) for it (the CI build is running off of my branch for now)
