### ISSUE TITLE
SDL version check is not cross-compile compatible

### ISSUE THREAD

**Issue by rofl0r** [schismtracker/schismtracker#187]
```
configure:5307: checking for SDL - version >= 1.2.10
configure:5394: i486-linux-musl-gcc -L/home/rofl/x-prefix/i486/lib -isystem /home/rofl/x-prefix/i486/include -o conftest -fdata-sections -ffunction-sections -Os -g -fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -mtune=generic -lSDL -I/home/rofl/x-prefix/i486/include/SDL -D_GNU_SOURCE -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,-rpath-link=/home/rofl/x-prefix/i486/lib conftest.c  -lSDL -I/home/rofl/x-prefix/i486/include/SDL >&5
configure:5394: $? = 0
configure:5394: ./conftest
Error loading shared library libSDL-1.2.so.0: Exec format error (needed by ./conftest)
configure:5394: $? = 127
configure: program exited with status 127
```
since you're using the sdl-config program anyway, i'd suggest simply calling `sdl-config --version` instead of trying to execute a cross-compiled binary.

**Comment by jangler** [comment]
I *really* don't know autotools that well, but as far as I can tell this decision originates in autotools and not in the Schism configure.ac script. I think you're supposed to pass the `--host` flag to the configure script if you're cross-compiling, and then this check is skipped.

**Comment by rofl0r** [comment]
autoconf isn't cmake, so it doesn't ship with 100 mb of library description files for all mainstream libraries. however it does have a mechanism to load all macros from a certain path.
in this particular case you're using AM_PATH_SDL https://github.com/schismtracker/schismtracker/blob/master/configure.ac#L63 which comes from $prefix/share/aclocal/sdl.m4 which in turn is installed there by SDL itself (that means someone who doesnt have sdl installed can't even generate the configure script via autoreconf). unfortunately that script is buggy & unmaintained and was written without cross-compilation in mind.

a program still using SDL1.2 should not use those macros, but instead just test whether compilation of a file that `#include`s `<SDL/SDL.h>` succeeds with `-lSDL`. that works almost everywhere and also for cross-compilation. if that fails you can try to simply execute `sdl-config`. if SDL is installed, it's available in $PATH.

i've written an in-depth guide about cross-compilation and issues like these in case you're interested: https://sabotage-linux.neocities.org/blog/5/

**Comment by jangler** [comment]
The changes in https://github.com/schismtracker/schismtracker/compare/58836fc...f2c30e8 work on my machine and in the CI targets, although now that I'm writing this I suspect that those `sdl-config` lines should use the result of `AC_CHECK_TARGET_TOOL` or something instead.

Not really related, but since you linked that blog, can I suggest identifying people by the names they currently use? It's not really ever helpful to say "\<deadname\> (nowadays known as \<name\>)". If you specifically need to connect someone with an former alias it can be alright to say "\<name\> (formerly known as \<deadname\>)", but in this situation I don't see why the former names are even necessary.

**Comment by jangler** [comment]
Closing, see comments on 03d8ad9.
