### ISSUE TITLE
Pattern Editor keys to go to previous/next note in channel

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#19]
This is something I've wanted for ages. Maybe depending on the column that the cursor is in it could go to previous/next volume/effect as well?

I'll add more thoughts when I'm not late for a thing.

**Comment by 0x5742** [comment]
Backspace goes to previous note _cell_, respects the multichannel (Alt-M) state, and works in all column positions. I'd expect this to mirror that.

Shift-A for previous slot with value and Shift-F for next slot with value were suggested on irc, and thinking a bit I rather like those, it'd be easy to jump around with pinky/forefinger and it follows the trend of using shift + non-notes.

Only problem I can see is if someone is for some weird reason used to typing shift-A/F instead of plain A/F in places where letter input is accepted (e.g. effect column) - I know on French keyboards the numbers and symbols are flopped so you've got to hold shift to type digits, it might make it harder to enter hex values on those layouts if you're used to just holding shift for numbers all the time. On the other hand French keyboards are weird anyway and I imagine the AZERTY gonks up typing notes, so I'd expect people with those layouts to switch their keyboard to US layout to use Schism anyway. (Or does the keyboard handler do some voodoo to remap these keys? That code has gotten disturbing.)

**Comment by jangler** [comment]
OK, I have never used multichannel before and have no idea what the use case even is, so I'll have to look into that.

**Comment by 0x5742** [comment]
NNA-less polyphony. Try Alt-MM, turn on channels 1-6, you can write a happy melody without having to hop between channels by hand.

**Comment by jangler** [comment]
This has been did, but after a lot of IRC discussion we decided on a different approach that ignores multichannel altogether. The helptext is:

```
Shift-A/F        Move to previous/next note/instrument/volume/effect
```

If you're in the note column, you seek a note; if you're in the effect column, you seek an effect; etc.
