### ISSUE TITLE
Contribute fixes back to OpenMPT?

### ISSUE THREAD

**Issue by asbjornu** [schismtracker/schismtracker#230]
Have the changes made to improve IT playback in Modplug been considered submitted back to OpenMPT so that part of Schism Tracker could be added as a Git Submodule or similar?

**Comment by j-schultz** [comment]
I have been porting playback fixes back and forth between OpenMPT and Schism Tracker **for years**. In fact, OpenMPT is probably more accurate in many aspects since it's my main project and I just backport fixes to SchismTracker if it isn't too much work.

Schism Tracker converted all of libmodplug to C while OpenMPT remains C++, so there is absolutely no chance to make project a submodule of the other.

**Comment by sagamusix** [comment]
I have been porting playback fixes back and forth between OpenMPT and Schism Tracker for years. In fact, OpenMPT is probably more accurate in many aspects since it's my main project and I just backport fixes to SchismTracker if it isn't too much work.

Schism Tracker converted all of libmodplug to C while OpenMPT remains C++, so there is absolutely no chance to make project a submodule of the other. In addition, Schism Tracker ripped out all the non-IT stuff from libmodplug, and is licensed under a different license, two more reasons making what you propose impossible.

**Comment by asbjornu** [comment]
@sagamusix, I see. Thanks for explaining!
