### ISSUE TITLE
Schism Tracker Plays and Stops on MacOS 11 but Shows a Blank GUI

### ISSUE THREAD

**Issue by playinmyblues** [schismtracker/schismtracker#246]
After reading about Schism Tracker in the The MagPi and trying it on an RPi 3B, it interests me. I installed it on my Mac running macOS 11.2.1. The GUI window pops up when it runs but it is blank. None of the pull down menus show anything.

If I open a .mod file by right clicking on it to open it in Schism, F5 works to play the file and F8 works to stop it.

As far as I can tell, it all works well on my RPi. I was using the built in audio jack and will have to try a USB audio card. - Just out of interest, not related to the Mac problem.

**Comment by jangler** [comment]
Does this solution work for you? https://github.com/schismtracker/schismtracker/issues/242#issuecomment-752693009

**Comment by aitorres** [comment]
Hello! I can confirm that the mentioned solution works on macOS Big Sur. I changed the driver from `sdl` to `opengl` and it is now working, Schism Tracker no longer opens up to a blank screen. 

I'd recommend adding that comment as a note somewhere on the README or the Wiki, so that it serves as a guide for macOS users.

**Comment by jrimmer-housecallpro** [comment]
The solution _should_ be to make `driver=opengl` the default in macos as mentioned by @jangler here: https://github.com/schismtracker/schismtracker/issues/242#issuecomment-753008013

But it seems to be somewhat less than trivial to do...

**Comment by jangler** [comment]
OpenGL should be the default for macOS as of the 20220125 release.
