### ISSUE TITLE
64-bit Win32 builds

### ISSUE THREAD

**Issue by a740g** [schismtracker/schismtracker#267]
Any reason we stopped releasing 64-bit Win32 builds? I know I can compile this myself from source. However, having the 64-bit zip release alongside the 32-bit one just makes it so much easier. 🙂

**Comment by jangler** [comment]
There's no 64-bit Windows build right now because our AppVeyor integration stopped working, and I haven't been able to fix it since I wasn't the person who set it up in the first place. So builds are currently done by hand. I can get 64-bit MSYS2 env set up to do that build, but I don't know how soon I will get around to it.

**Comment by jangler** [comment]
Resolved via #272. New release has 64-bit Windows build.
