### ISSUE TITLE
no channels

### ISSUE THREAD

**Issue by ghost** [schismtracker/schismtracker#269]
_

**Comment by ghost** [comment]
_
![image](https://user-images.githubusercontent.com/80146817/127749404-ffec6dd6-ce15-46fd-b3c0-7763c89545dc.png)

**Comment by ghost** [comment]
is channel actually toggleable or way to unzero channel activity ? can this program n

**Comment by ghost** [comment]
I'm away from my computer so I can't replicate the issue you're having, but Alt-F9 and Alt-F10 are "toggle channel" and "mute channel" respectively, does that help?

**Comment by vcaputo** [comment]
> is channel actually toggleable or way to unzero channel activity ? can this program not suck dicks

Schismtracker is a clone of the venerable Impulse Tracker, which I gather you're not already familiar with.

Instead of slinging insults in a github issue, you might want to go find a Impulse Tracker or schismtracker tutorial to read/watch.  I'm sure youtube has some guides.

There are many happy users of this tool, but they're likely already familiar with how Impulse Tracker or Scream Tracker functioned.  It's definitely not tailored for new users and hand-holding them into getting productive with it.
