### ISSUE TITLE
Failed to start CoreAudio: AudioUnitInitialize

### ISSUE THREAD

**Issue by atonusgit** [schismtracker/schismtracker#287]
It seems there's an issue with starting CoreAudio in Schism Tracker.

I get this message to Message Log Viewer when I load a module:

`Failed to start CoreAudio: AudioUnitInitialize`

macOS 12.2.1
Schism Tracker version 20220125

**Comment by jangler** [comment]
Looks similar to #231. My impression from a web search is that this is an SDL 1.2 problem that was fixed in 2017 – but official new releases of SDL 1.2 stopped in 2012. You could try using an unofficial SDL 1.2 dylib or using https://github.com/libsdl-org/sdl12-compat to run Schism on SDL2 instead.

**Comment by Manwe-SandS** [comment]
I've got the same issue. It would be great if the next version/build of Schism Tracker will be tested on the latest MacOS before release, so a user can just run it without fixing/patching/whatever using Terminal. We are just musicians, after all, not developers.

**Comment by jangler** [comment]
It's not really a matter of testing in this case; #231 was reported in 2020. The issue is that decisions made by Apple and the SDL project mean that properly fixing this problem requires a major code overhaul. It's been discussed and attempted for years, but since Schism doesn't really have any dedicated developers, it's never gotten done.

**Comment by jangler** [comment]
@mrpapersonic has kindly contributed a PR that would package the latest development version of SDL 1.2 with Schism builds instead of the latest stable release version. Can someone with this issue test using https://github.com/schismtracker/schismtracker/suites/6335965951/artifacts/228102064 and report whether this does indeed fix the issue?

**Comment by Manwe-SandS** [comment]
Wow, it works now! Thank you a lot, Jangler!

**Comment by atonusgit** [comment]
Works here too! Kudos @jangler!
