### ISSUE TITLE
[MOD file import] Incorrect "Set speed" effect import

### ISSUE THREAD

**Issue by ivan-tat** [schismtracker/schismtracker#299]
Branch: [master](https://github.com/schismtracker/schismtracker/tree/master)
Version: [35429cd4ce993dcc6ffb7029a36e3bcebc01da33](https://github.com/schismtracker/schismtracker/tree/35429cd4ce993dcc6ffb7029a36e3bcebc01da33) (latest)

Now (incorrect):
MOD Effect | Parameter | Meaning | Schism Effect | Meaning
---|---|---|---|--
Fxx | xx=00..1F | set speed to xx | Axx | set speed to xx
Fxx | xx=20..FF | set tempo to xx | **A**xx <= incorrect | set **speed** to xx

Should be (correct):
MOD Effect | Parameter | Meaning | Schism Effect | Meaning
---|---|---|---|--
Fxx | xx=00..1F | set speed to xx | Axx | set speed to xx
Fxx | xx=20..FF | set tempo to xx | **T**xx <= correct | set **tempo** to xx

**Comment by sagamusix** [comment]
Cannot confirm that. Tempo commands are imported just fine here.

Relevant code: https://github.com/schismtracker/schismtracker/blob/fb85b00678064708ebb36668ab382afc80d1fe0a/player/csndfile.c#L1331

Maybe you tried to import a MOD with an `F20` command? For legacy reasons that specific command parameter is treated like in Scream Tracker 3 and Impulse Tracker (speed instead of tempo) but `F21` and above import as tempo just fine here.

**Comment by ivan-tat** [comment]
Sorry, you are right. I used `F20` command. I didn't know that feature. I think it's better to close this issue with "not a bug" or "feature" label (but I didn't find right labels)... Or "stupid user" :)

**Comment by jangler** [comment]
Wait, just so we're clear – is there a problem with `F20` import from MOD?

**Comment by sagamusix** [comment]
`F20` is murky waters - Most players treat it as Set Speed (the way it originally worked) but Scream Tracker 3 treats it as Set Tempo (probably off-by-one error), which is a behaviour Impulse Tracker inherited from Scream Tracker 3. ModPlug Tracker / OpenMPT used to follow this behaviour but now behaves like ProTracker / FastTracker (i.e. `F20` is Set Tempo). Due to Schism's heritage, I would say that treating it as Set Speed is appopriate.
