### ISSUE TITLE
minipop_slide: the mouse cursor is not always above the knob

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#30]
Currently if you click to get the minipop_slide, the mouse is not moved to the knob, so the knob then becomes moved away far from its current place.
For convenience, the cursor should jump to the knob in lieu. So you can e.g. change pattern 2 to pattern 3 without carefully moving it back to where it should be.
Alternatively, the minipop_slide could be placed with an offset that the knob appears under the cursor.

And additionally being able to change the value with the mouse wheel when the cursor is above the number would be pleasant.

**Comment by jangler** [comment]
Interesting; I never knew this feature existed (I don't use the mouse at all). I don't like the behavior very much. In addition to the problem you mentioned, you have to precisely keep your mouse over the widget while sliding. IMO all sliders in Schism should keep sliding to the mouse position until the mouse is released.

As for this issue, warping the mouse would be much more practical than placing the popup with an offset, since the popup itself is quantized to the grid that most of Schism is drawn to.

**Comment by HybridDog** [comment]
> I never knew this feature existed 

Some music files (skaven) contain multiple tracks in one tracker file, to play them one should start playing from specific patterns. And in schism you need to select the pattern.
In my experience using the slider and then pressing F7 works best.
How do you switch patterns?

**Comment by jangler** [comment]
Either -/+ on the F2 or F5 screens or up/down/pgup/pgdn on the F11 screen, depending on what I'm doing.

**Comment by HybridDog** [comment]
Why does schism not show the pattern names (OpenMPT does)?

**Comment by jangler** [comment]
Because there aren't any ;(

https://github.com/schismtracker/schismtracker/wiki/ITTECH.TXT#impulse-pattern-format

**Comment by sagamusix** [comment]
Pattern names are a ModPlug extension. https://wiki.openmpt.org/Development:_OpenMPT_Format_Extensions
I suppose you are trying to play the Bejeweled soundtrack in Schism (as you mention Skaven), in which case you should probably really use OpenMPT instead, since it uses several features not supported by Schism or Impulse Tracker at at all, such as DMO effect plugins.

**Comment by HybridDog** [comment]
thanks, l got the sound tracks there: http://www.futurecrew.org/skaven/music_tracker.html
OpenMPT tells that plugins (e.g. Echo) are missing, schism doesn't. Does schism support them or does it ignore them without telling they're missing?

**Comment by sagamusix** [comment]
That's correct, plugins are also a ModPlug extension hence Schism won't warn about the absence of them. I suppose you are using OpenMPT through wine, in which case you can get the Echo plugin to work like this: https://forum.openmpt.org/index.php?topic=5448.0

**Comment by HybridDog** [comment]
thanks, l assume that's the reason why openmpt123, which l installed with libopenmpt using $ checkinstall, didn't tell plugins were missing.

**Comment by sagamusix** [comment]
Exactly, openmpt123 has DMO emulation built-in, it will probably added to OpenMPT itself in the next version too.
(sorry for off-topic :)

**Comment by jangler** [comment]
> IMO all sliders in Schism should keep sliding to the mouse position until the mouse is released.

Looks like this might be harder than I thought. I could make it so that the active widget focus doesn't change while the mouse is depressed, but I'm trying to think if that would break anything else.

**Comment by jangler** [comment]
Implemented mouse warping in `minipop_slide()`, but for some reason it behaves differently for the different fields. I guess different fields call the function differently (incorrectly)? Octave and Speed are spot-on. Sample, Pattern, and Row decrease by one every time the function is called. Order resets to zero. Tempo increases by 30 each time. _(Edit: this was partially due to my own stupidity.)_

I notice that the Sample popup doesn't have a label, so that's one easy thing to fix. _(Edit: fixed.)_

**Comment by jangler** [comment]
There's also a bug here in that the Order slider only changes the cursor position in the F11 order list, but the initial value it gets is dependent on the currently playing order. I won't change the functionality of the slider, so I'll just make the initial value dependent on the cursor position instead.

**Comment by jangler** [comment]
Also, the program crashes if you use the slider when the order list is empty.

**Comment by jangler** [comment]
Order slider bug fixed in 07ac6962d2f86f4e5da7c92b9635c9dd95aeb6fd; mouse warp implemented in fb6ffc814a0b0e37c3d2bc8fdc51ce598e45a611.

**Comment by HybridDog** [comment]
@jangler l just noticed that mouse warping only works with the default window size.

**Comment by jangler** [comment]
Well, shoot. Thanks for the tip.

**Comment by jangler** [comment]
Should be fixed now. Can you test it out for me?

**Comment by HybridDog** [comment]
It works.
By the way, there's another problem: The areas where mouse clicks for spawning the minipop are recognized have a left one-character-sized unwanted offset:
![2016-09-15-083754_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/18540738/0cbcea7c-7b21-11e6-8d6c-20a8ae25c9d7.png)
the red box shows where you need to click, the blue one shows the area without the unwanted offset

**Comment by jangler** [comment]
OK, thanks. I'm going to open a new issue for that, since it's quite different code.
