### ISSUE TITLE
SDL2 port (Mac OS X SDL 1.2 deprecated)

### ISSUE THREAD

**Issue by asbjornu** [schismtracker/schismtracker#33]
This might be related to #23 which then caused a crash, but after self-recompilation instead causes this warning to be dumped in the console:

```
2016-08-15 19:41:45.264 schismtracker[77281:6776834] 19:41:45.264 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```

Since this is just a warning (on OS X 10.11.6, I don't know the state on macOS 10.12), I don't think we need to rush to fix this, but we might keep this issue here to track it and share ideas on how to fix it.

**Comment by jangler** [comment]
Weird, sounds to me like this is a SDL 1.2 thing.

**Comment by asbjornu** [comment]
@jangler Yes, perhaps compiling against SDL 2.x would help?

**Comment by ghost** [comment]
We thought about it but SDL 2 is very different to SDL 1 - you can't just "compile against" SDL 2, we would have to rewrite all the bits of code that talk to SDL anywhere and it would be a mammoth task.

It is a good idea, but just loads of effort.

**Comment by asbjornu** [comment]
Are we sure the warning is caused by SDL 1, then? If not, taking on the mamoth task of rewriting against SDL 2 would be in vain. :grimacing:

**Comment by jangler** [comment]
I don't think we need to worry about that ;)

I also don't know the first thing about a Carbon Component Manager or what it is, but anything that has to do with actual audio playback APIs will be handled by SDL. Schism does not implement code for interfacing with the various sound card APIs or sound servers; that's all SDL biz.

**Comment by jangler** [comment]
Yeah, OK, it's SDL: https://bugzilla.libsdl.org/show_bug.cgi?id=3127

**Comment by asbjornu** [comment]
Ah, look at that. Seems like there's an [SDL 1.2 patch](https://bugzilla.libsdl.org/attachment.cgi?id=2272&action=diff) in there as well, but from what I read it won't be applied since SDL 1 is deprecated. Is it possible to apply the patch ourselves before compiling?

**Comment by jangler** [comment]
Well, the Schism build process doesn't normally involve compiling a custom build of SDL! But if down the line this becomes a concrete problem (what's a version 3 audio unit, anyway?), then that might become a necessity for builds targeting the macOS version that breaks things.

**Comment by asbjornu** [comment]
I learned from the [Windows build instructions](https://github.com/schismtracker/schismtracker/blob/master/docs/building_on_windows.md) that there's already [a fork of Schism Tracker built against SDL 2](https://github.com/davvid/schismtracker/tree/sdl2). It would be awesome if its author @davvid could do a "proper" fork and do a pull request of those changes, no? My assumption is that we will need to upgrade from SLD 1.x to 2.x some time in the future anyway.

**Comment by jangler** [comment]
Maybe! No one likes to obsolete things as much as Apple does, though. I bet it'll be a good while before SDL 1.2 stops being supported on other platforms.

**Comment by asbjornu** [comment]
True. However, would upgrading to SDL 2 have any downsides? Does it perhaps drop support of any platforms we want to continue supporting? I have no idea. :confused:

**Comment by davvid** [comment]
Ah, I had not realized that development had moved here to github.  I'll try to work together some patches that might help a port along.

One downside is that we lose support for direct framebuffer support on linux (it still works fine under X), and the window no longer resizes.  Maybe y'all can help me figure out what I broke about the resizing ;-)

I did contact someone that had started working on adding fbdev support to SDL2 but they stopped working on it after they started using Xfbdev.  Maybe that'll materialize sometime in the future, but not sure if that's worth not using SDL2.

The keyboard handling is not really right in my davvid/schismtracker#sdl2 branch.  SDL2 reworked how keys are used, so I was able to make most stuff work, but extended DOS codepage characters probably don't work as expected.

In a modern program we'd probably try to use utf-8 in there, but I figured that it probably has implications for the .it file format, so we'd need to stick to some DOS ascii codepage I would imagine. I need to study that part of the code better since I kinda just papered over it.

It was functional enough for authoring stuff, tho, so that was good enough for me at the time when SDL1 was not working on OS X but SDL2 did.

The fullscreen feature is what stopped working after upgrading OS X, and I think I managed to get my settings saved with fullscreen mode set true, so I was pretty motivated at the time (even tho I could've just fixed my settings instead ;-)) 

I let my friend borrow my OS X laptop so I only ever really use my linux laptop these days so I can't verify the current state of OS X SDL things.  Is SDL1 still maintained?  I kinda assumed that they stopped caring about newer OS X versions.

I'm going to rename my mirror repo to schismtracker-legacy and do a proper fork soon.  If you see my `sdl2` branch disappear, you'll be able to find it in the schismtracker-legacy repo.

**Comment by jangler** [comment]
No, SDL 1.2 is deprecated and not maintained. Thanks for all the info, that's very helpful.

**Comment by jangler** [comment]
@davvid Do have any updates on the SDL2 version? @esaruoho reminded me that this is still a vague looming threat.

**Comment by esaruoho** [comment]
I've been able to install SDL 1.2.15 via Homebrew without any issues, and got it running on macOS High Sierra (10.13.2)

**Comment by Luraktinus** [comment]
SDL 1 is dead and unsupported

its really time to focus on sdl2,

**Comment by algorev** [comment]
Yes. It still works, but something should be done about that.

**Comment by alexmyczko** [comment]
https://wiki.libsdl.org/MigrationGuide
