### ISSUE TITLE
F11 not working on MacOS since release 20220807

### ISSUE THREAD

**Issue by mvoltron** [schismtracker/schismtracker#330]
F11 (order list) does not function on MacOS builds since 20220807 until the latest (20221020).
F1…F10 work, F12 works. F11 does nothing.

Tested on MacOS 11 Big Sur and MacOS 13 Yosemite on MacBook Pros with internal and external keyboards both with F-keys set up as standard function keys (F1…F12 directly) and as volume up-down etc keys, where you have to hold down Fn to get the standard F1…F12 functions.

I was using the 2022 May build before where F11 functioned perfectly.

**Comment by digistorm79** [comment]
I don't know if it's helpful, but on my MacBook Pro with M1 Pro chip and macOS 13 Ventura, F11 works just fine (on version 20221020). So it affects not all Macs.

**Comment by asbjornu** [comment]
F11 also works fine in version `20220905` on macOS Big Sur 11.7.

**Comment by mvoltron** [comment]
Solved! Mission Control was stealing the F11 (F11 = show desktop). I've never used it and do not recall setting it up, therefore it was not an obvious culprit. Schism being in full screen it ignored showing the desktop, hence no reaction to pressing F11. Thanks for your replies, it forced me to dig deeper.

However, in earlier builds (up to 20220506 and older) F11 works in full screen Schism as expected. As far as I understand Schism was switched to SDL2 after that. May it be that SDL1.2 was overriding Mission Control in full screen mode? When I switch to windowed mode in 20220506, F11 starts working for Mission Control and is not opening order view in Schism. 

Anyway, solved for me by removing F11 from Mission Control.

![mission control](https://user-images.githubusercontent.com/117210082/206095914-696ca9fd-cd4d-4350-af98-8784b5402a63.png)

**Comment by jangler** [comment]
Thanks for looking deeper! Looking at the code, I'm guessing this happens because SDL2 versions of Schism use `SDL_WINDOW_FULLSCREEN_DESKTOP` rather than `SDL_WINDOW_FULLSCREEN`, which the docs describe as a "fake" versus a "real" fullscreen. I'm not sure whether this distinction was present in SDL1.2, when Schism used the `SDL_FULLSCREEN` flag.

For me, `FULLSCREEN_DESKTOP` is a bit more convenient because it doesn't require a video mode change, but I guess an advantage of true fullscreen would be that keys Schism uses couldn't be intercepted by other programs. I'd be open to adding a config file option to choose between the two if anyone specifically wanted the option to use "real" fullscreen.
