### ISSUE TITLE
Pattern Editor: Pattern Editor Options (2x F2) window remains on screen in other screens

### ISSUE THREAD

**Issue by kserp** [schismtracker/schismtracker#363]
version 20221201

The Pattern Editor Options overlay remains visible when you switch to a different screen.
I have this a lot when I want to switch from Pattern Editor (F2) to Sample List (F3) and accidentally tap F2 first.
Small nuisance but would be awesome if fixed :)

**Comment by pedrohex** [comment]
I don't find anything wrong. Pressing F2 instead of F3 by mistake, it will open the Pattern Editor Options.
If I press the F3 nothing happens because the Pattern Editor Options is working as a Dialog. We either need to close with escape or accept the changes with the Return key. 
Am I missing something here ?

**Comment by mrpapersonic** [comment]
This is OS X specific and it has to do with the [macosx-core.m](https://github.com/schismtracker/schismtracker/blob/master/sys/macosx/macosx-sdlmain.m) file that handles function keys, among other things. For how many problems it makes (#358, #357, probably more), it's likely better to just remove the menu bar altogether and rely just on key inputs like every other platform.
