### ISSUE TITLE
Explanation of the mixing modes

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#37]
The mixing modes (no interpolation, linear, cubic spline and 8-Tap FIR Filter) aren't documented for schism (l couldn't find doc).
l'm wondering which impact exactly they have on cpu usage, sound quality and deviation from the original/supposed sound.

l could hear some differences: no interpolation sounds noisy (of course), linear sounds like cubic and 8-Tap FIR Filter lacks volume of high frequency sounds.

**Comment by jangler** [comment]
If you want a graphical analogy, try resizing images with linear, cubic, and no interpolation. That's more or less what happens to the waveform under those interpolation modes.

As you might guess, no interpolation is the least expensive, and I'd guess that linear < cubic < FIR. The reason for different interpolation modes is that sample rates usually don't match the mixing rate of Schism and the samples get pitched up and down anyway, similar to scaling an image.

"Sound quality" and "original/supposed sound" are entirely subjective and variable. Different modules may be written using a different interpolation mode. I write a lot of modules with no interpolation in mind, even though it's the least sophisticated of the modes. When in doubt, use linear interpolation, since it's the default for most XM/IT trackers (but XMs are second-class citizens in Impusle and Schism; you should probably use a different tracker to play those back anyway). OpenMPT might use cubic by default?

An explanation of such is probably beyond the scope of Schism Tracker's documentation per se, though.

**Comment by HybridDog** [comment]
> An explanation of such is probably beyond the scope of Schism Tracker's documentation per se, though.

l think about a simple explanation with pictures, e.g. screenshots of audacity showing the same part recorded with different filters.

Does cubic interpolation destroy/round sawtooth and square waves?

Why do bright noises sound quiet if l use 8-Tap FIR?

openmpt123 shows `Filter: 8 taps`, so does it use the FIR filter?

**Comment by jangler** [comment]
Well, my point is that these things aren't unique to Schism Tracker; you can find explanations as detailed as you want by looking them up on the web.

The degree to which interpolation "rounds" a particular waveform depends on its "resolution". The classic example of a module "chip" waveform is a 32-sample waveform with a sample rate of 8363 Hz. This will be rounded quite noticeably by interpolation, but the same waveform with a period of 184 samples and with a sample rate of 48000 Hz will be less noticeably rounded.

Bright noises sound quieter because bright noises have high-frequency overtones, which interpolation necessarily dampens at lower sample rates.

I have never used OpenMPT or related tools, but yes, that looks like a FIR filter to me.

**Comment by jangler** [comment]
Here's a relevant page from the OpenMPT wiki: https://wiki.openmpt.org/Manual:_Setup/Mixer

**Comment by HybridDog** [comment]
Thanks for your patience,
a link to an explanation of the available settings at the schismtracker wiki would be convenient, imo it's not easy to find a simple and short explanation and comparison of the filters being used for sound.

**Comment by sagamusix** [comment]
> OpenMPT might use cubic by default?

OpenMPT / libopenmpt / openmpt123 use 8-tap FIR by default. Note that this is not necessarily the same FIR filter as Schism uses. It's just a class of filters, and there are many ways to implement it.

> Why do bright noises sound quiet if l use 8-Tap FIR?

Because the theoretical goal of a good resampling filter and the practical crappiness of old module samples don't mix.
In a perfect world, resampling from one frequency to another would not add any new frequencies to the mix, but due to aliasing artefacts, you always get some high-frequency noise that's not supposed to be there, especially with cheap resampling filters (no interpolation, linear and cubic).

Now, if modules were only using high-quality samples that already contain high-frequency content, e.g. samples with a sample rate of 44 or 48 kHz, you could always just use the highest quality resampling filter and everything would sound bright and nice. However, oldskool modules rather use samples that have a sample rate of, let's say, 8 - 22 kHz, which means that these samples technically do not contain any frequency material above 4 - 11 kHz. But if you resample these samples to the target frequency (e.g. 48 kHz) with no or linear interpolation, the cheap algorithm cannot prevent frequencies above the aforementioned ones from being added to the mix, so these low-quality samples suddenly sound much brighter than they should in theory.
This is why oldskool mods typically sound better with worse resampling (and why so many people hate 8-tap FIR filters without understanding what's going on), while a modern, high quality module with good samples will sound better with 8-tap FIR, because your samples sound good already.

**Comment by jangler** [comment]
I added [a wiki page](https://github.com/schismtracker/schismtracker/wiki/Mixing-Modes) that just links to this discussion, but I'll keep the issue open for a while in case people have more to say.

**Comment by sagamusix** [comment]
I rewrote my comment from above a bit for inclusion in the OpenMPT FAQ, in theory you can copy it over to the wiki as well with slight modifications: https://wiki.openmpt.org/Manual:_Frequently_Asked_Questions#Why_do_old_modules_and_chiptunes_sound_muffled_in_OpenMPT.3F

**Comment by HybridDog** [comment]
Since some tracker files can store content like pattern names although they're not supported officially by the file format, could you allow defining the filter to be used in the file that, if the player heeds it, the file is played with this filter?

**Comment by sagamusix** [comment]
OpenMPT can do that in its own MPTM format, but I deliberately left the option out in the IT/XM formats. It's 2016, and we do not want to repeat the mistakes made 10 years ago where ModPlug/OpenMPT added tons of new features to IT/XM that noone else ever supported.

**Comment by HybridDog** [comment]
Can the resample methods which pulseaudio uses (libspeexdsp and libsamplerate) be used to mix the samples in schismtracker?

**Comment by sagamusix** [comment]
No, these kind of resamplers are not typically suitable for the kind of resampling trackers do. They might be using IIR filters instead of FIR (which have less desirable phase characteristics when changing pitch), and typically are not intended to be used in a scenario where the sample rate changes. In a tracker, the sample rate can change on every tick, e.g. by means of vibrato or portamento.

**Comment by HybridDog** [comment]
I assume, if I set the mixing rate in schismtracker to something high, e.g. 192000, the samples are resampled to this rate in schismtracker and then pulseaudio resamples it to 44100 using speex. Would this harm or improve quality?

**Comment by sagamusix** [comment]
That is called oversampling and if done properly improves the sound quality.

**Comment by HybridDog** [comment]
Unfortunately there's music which sounds better with a simple (e.g. linear) resampling method because the high frequency noise makes that music sound better (e.g. when there're cymbals instruments).

**Comment by sagamusix** [comment]
Yes, I've explained that in the long-ish comment above. Even with linear interpolation, oversampling can still sound nicer.

**Comment by HybridDog** [comment]
I've got another question: Is the [Smoothstep](https://en.wikipedia.org/wiki/Smoothstep) function suitable for resampling, maybe as a compromise between linear and nearest filter?

**Comment by sagamusix** [comment]
Why would that be a compromise between those two? It has nothing to do with either of them. That said, I don't see why you would want to use it. Sinc filters are mathematically optimal, so why settle with anything worse? Smoothstep is something you could e.g. use for volume ramping, but I have never heard anyone use it for audio or graphics.

**Comment by HybridDog** [comment]
> Why would that be a compromise between those two?

With the linear filter there are spikes (jump in the derivation) when calculating the value near a sample point but between two points it behaves like a straight line (constant derivation),
and with nearest neighbour the derivation is zero (constant) around the sample point but the value jumps between two sample points.
With smoothstep the derivation is zero near sample points (resembling nearest neighbour) and almost behaves like a straight line between two points (resembling linear interpolation). So maybe it can combine the intentional high frequency noise of linear and nearest neighbour interpolation.

**Comment by HybridDog** [comment]
I've tested smoothstep: [smoothstep_test.zip](https://github.com/schismtracker/schismtracker/files/2472471/smoothstep_test.zip)
