### ISSUE TITLE
How to enter a digraph?

### ISSUE THREAD

**Issue by mouseboard** [schismtracker/schismtracker#382]
Pressing Ctrl twice brings the "Enter digraph:" text out, but pressing any letter makes it disappear. This is the same for entering Unicode (by holding Ctrl Shift), but for some reason it works in the Save Module screen.

**Comment by mrpapersonic** [comment]
To enter a digraph, I believe you have to press CTRL and then press and
hold it again, then entering the right keys. It only really works in the instrument list and message editor iirc because of the way schism's internal VGA emulation works. This may also be a limitation in IT, but I'm not really sure.

The current method of digraph entry is stupid and outdated anyway and will be outshined by proper text entry support provided by #443.

**Comment by mouseboard** [comment]
Thanks.
