### ISSUE TITLE
Is there a way i can use it on Mac OS 9.2?

### ISSUE THREAD

**Issue by hornlisalat7** [schismtracker/schismtracker#386]
I recently tried to install SchismTracker on my iMac G3, unfortunately, the Mac Version from the Website isnt working. Any Help or Place where I could download a supported Version?

**Comment by vcaputo** [comment]
There's nothing preventing it in the code, but AFAIK none of the regular builds target pre-OSX era Mac.

If you can get your hands on a build environment, I think the question comes down to more "does SDL2 support old MacOS?" which I don't know for certain.

**Comment by mrpapersonic** [comment]
Modern SDL2 only supports back to 10.6 (more recently, 10.7) last I checked. You can always use the last SDL 1.2 version under the tag `sdl1` for classic Mac OS.

**Comment by mrpapersonic** [comment]
Current master branch creates builds for classic mac os, only tested on mac os 9.2.2 for now. I wouldn't recommend it at all for actually making anything, since it has fairly bad performance (though much better than os x on the same computer at least)

It requires the multiprocessing library to run (for threads and semaphores) which means its probably limited to just OS 9. Any system that can't run OS 9 though will probably croak just trying to run schism anyway.
