### ISSUE TITLE
Both Resonance and Filter are enabled, but it's not supposed to be in the original .it format

### ISSUE THREAD

**Issue by babatunde3** [schismtracker/schismtracker#391]
I compared both trackers OpenMPT and Schism Tracker: In OpenMPT, Both are enabled, but no reso and the cutoff parameter Z7F is "Off", but in Schism Tracker, it's on even Cutoff and reso are enabled.

Can you analyze this problem with both trackers along with the original with mmx enabled? Thanks

~Keygenism from Moonshine

**Comment by sagamusix** [comment]
As always, it's impossible to say anything about this without having an example file to look at.

**Comment by babatunde3** [comment]
https://drive.google.com/uc?export=download&id=103MzSShFfpayowLm50wHMm-71xXe66lg

**Comment by sagamusix** [comment]
That file appears to have been previously saved with an older version of (Open)MPT or with some other, less compatible tracker, because several [compatibility playback flags](https://wiki.openmpt.org/Manual:_Compatible_Playback) are not set to their defaults. Schism Tracker plays the file the correct way, i.e. like Impulse Tracker would. OpenMPT will do the same if you go to Song Properties and then click "Set Defaults".
