### ISSUE TITLE
UNI support

### ISSUE THREAD

**Issue by Corsaka** [schismtracker/schismtracker#392]
this is an extremely niche use-case for a set of old .uni files i cannot find versions of in any other format. i recognize barely anyone else will have the same issue and thus it's horrifically low-priority. libmikmod [has a loader](https://github.com/sezero/mikmod/blob/master/libmikmod/loaders/load_uni.c), but doesn't allow editing of the file, which does amaze me because they created the format to begin with. i am nowhere near skilled enough in C or trackers to know whether this is even possible, whether it's a worthwhile inclusion for schism, or how difficult an implementation would be - i can only ask.

**Comment by vcaputo** [comment]
I thought libmikmod was strictly about playback, and not editing?

Does any tracker save/export to this format?

**Comment by sagamusix** [comment]
> I thought libmikmod was strictly about playback, and not editing?

Almost every module playback library of the 90s had its own internal proprietary format - usually to save a bit of space and to improve loading speed, because those formats are usually a direct representation of the library's internal state. So yes, editing those files was not a goal, maybe even explicitly an anti-goal: A second reason for using such a format would be that the music included with a game or demo would not be editable with any common tracker back then, which may be desirable to some people.

As a direct consequence of this, most UNI files have a known alternative representation in one of the other, editable module formats. Direct support for UNI files in a tracker focussing on a single format like SchismTracker can be difficult, because the format supports all the features that MikMod has to support for playing a variety of formats. It's not impossible, of course, as all the other loaders in Schism Tracker show, but it adds a lot of duplicated complexity if playback should be as close as possible to the original format.

MilkyTracker has a UNI loader that could be used to import UNI files and resave them as MOD/XM. You can use Schism Tracker or OpenMPT to convert them to S3M/IT if that's required.

**Comment by Corsaka** [comment]
milkytracker - hail - thank you so much. i understand not directly supporting uni, and clearly the 90s was a horrible time for file standardization lmao

i'll close this as it's evidently not feasible

**Comment by sagamusix** [comment]
It's definitely feasible, but given the small amount of contributors of this project, it would definitely not be very likely to be implemented anytime soon. So I guess it's fine to close since there is a workaround available for you.

**Comment by vcaputo** [comment]
> > I thought libmikmod was strictly about playback, and not editing?
> 
> Almost every module playback library of the 90s had its own internal proprietary format - usually to save a bit of space and to improve loading speed, because those formats are usually a direct representation of the library's internal state.

I suspected this was the nature of the format, but figured persisting/(de)serializing the normalized IR was more for debugging/development purposes than anything targeting end-users.

> So yes, editing those files was not a goal, maybe even explicitly an anti-goal: A second reason for using such a format would be that the music included with a game or demo would not be editable with any common tracker back then, which may be desirable to some people.

That makes sense. I hadn't considered the deliberate sealing angle something like demo or proprietary game devs would appreciate...

Thanks for chiming in and explaining it.
