### ISSUE TITLE
Can't run 64-bit Linux build on Debian 12

### ISSUE THREAD

**Issue by pbackus** [schismtracker/schismtracker#396]
Attempting to run the latest schismtracker release build (20231029) on Debian Linux 12 fails with the following error:

> `./schismtracker: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory`

Because libflac8 [was included in Debian 11, but is not included in Debian 12][1], this dependency cannot be satisfied.

[1]: https://packages.debian.org/search?keywords=libflac8

**Comment by pbackus** [comment]
According to `ldd`, schismtracker-20231029 depends on both libflac8 and libflac12:

```
	linux-vdso.so.1 (0x00007ffe4b8a2000)
	libFLAC.so.8 => not found
        [...]
	libFLAC.so.12 => /lib/x86_64-linux-gnu/libFLAC.so.12 (0x00007fec00a34000)
        [...]
```

It seems like probably only one of these should be necessary.

**Comment by vcaputo** [comment]
`ldd` doesn't show just the immediate dependencies of the specified file/object, it'll show you dependencies pulled in by others (recursively).

You can use `readelf -d` to see what's in the dynamic section as one way to identify an elf object's direct dependencies:
```
$ readelf -d schismtracker

Dynamic section at offset 0xdb640 contains 32 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libFLAC.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXv.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
...
```

I suspect your libFLAC.so.12 is coming from libSDL2, it's not a dep of the latest linux schismtracker release.

Edit: BTW, `ldd` also isn't the greatest tool to use for this kind of thing (see the Security blurb in the ldd(1) man page).

**Comment by pbackus** [comment]
Ok, good to know.

You may still want to consider upgrading the version of libFLAC schismtracker depends on directly to one that's more widely available.

**Comment by vcaputo** [comment]
Glancing at the github workflow for building the linux release, It's just asking for the libflac-dev package in ubuntu-latest for build-linux:
https://github.com/schismtracker/schismtracker/blob/master/.github/workflows/build.yml#L214

So it might just need a new release built and pushed if there's a newer ubuntu-latest where libflac-dev maps to libflac12.

@mrpapersonic wdyt?

**Comment by mrpapersonic** [comment]
libflac12 is only in Ubuntu >=23.04 (github's runners are at 22.04 LTS) so that wouldn't work.
Though tbh it's odd to distribute just binary without any of the libraries. Looks like more of a packaging problem than anything; should we provide something like an appimage instead?

**Comment by vcaputo** [comment]
Static linking might be an option, but it might require treating the linux build more like the macos/mingw builds are performed; building the dependencies from source.

Last time I tried static linking an sdl2 game using a debian host, it failed just because the -dev packages inexplicably didn't include some .a files even though you'd get them if you built the packages from source yourself.  Some distros/package maintainers seem actively hostile to static linking.

At least schism is basically a standalone executable, and doesn't mess with nsswitch junk the glibc camp claims is incompatible with static linking.  It's a pretty ideal candidate for -static to overcome this b.s.

**Comment by mrpapersonic** [comment]
SDL shouldn't need static linking because all the versions are all ABI compatible themselves, so really we'd only have to build libogg and libflac statically and depend on the user to install SDL themselves. With it we just have to bundle [Xiph.Org's BSD license](https://github.com/xiph/flac/blob/master/COPYING.Xiph) with Schism (sidenote: this should really be in the mingw and macos builds as well since we provide binaries there too).
