### ISSUE TITLE
Bug: Can’t handled .IT files that contain 256 patterns in the order list

### ISSUE THREAD

**Issue by jpage8580** [schismtracker/schismtracker#401]
I tested an original .IT file that contained 256 patterns in the order list. 

the end marker (FF) is then appended to that, causing the final size to be 257. 

This then fails to load in SchismTracker as it checks for that size being > 256 for a file being corrupted. 

File does load correctly in MPT, so was able to remove a pattern in that, resave and then it loaded OK in SchismTracker.

**Comment by mrpapersonic** [comment]
Sounds like https://github.com/schismtracker/schismtracker/blob/master/include/sndfile.h#L25 has to be incremented?

**Comment by jpage8580** [comment]
I’d presume so, but didn’t know if anything else (buffer allocation and
such like) were fixed to 256. I basically just looked at how the “corrupt
file” error could trigger, and once I figured it out, removed a pattern.

**Comment by sagamusix** [comment]
I encountered this a while ago as well but didn't have a fix ready. Since the extra (257th) order item can only be a `---` pattern, I think that setting `MAX_ORDERS` to 257 is not a good fix here (you don't want the user to be able to edit this item, or show it in the GUI, etc.). This should be handled purely in the loader code.

**Comment by vcaputo** [comment]
> Since the extra (257th) order item can only be a `---` pattern, I think that setting `MAX_ORDERS` to 256 is not a good fix here (you don't want the user to be able to edit this item, or show it in the GUI, etc.). This should be handled purely in the loader code.

That reflects my vague thinking when I gave this a cursory look initially, but haven't had the time to dig into it.  It smells like one of those common off by one comparison < vs. <= mistakes, the max orders is still correct at 256.

**Comment by sagamusix** [comment]
No, it's not really an off-by-one error, it's just that the code doesn't anticiapte this situation - it's even documented in the saving code (but curiously not in the loading code):

```
	/* IT always saves at least two orders -- and requires an extra order at the end (which gets chopped!)
	However, the loader refuses to load files with too much data in the orderlist, so in the pathological
	case where order 255 has data, writing an extra 0xFF at the end will result in a file that can't be
	loaded back (for now). Eventually this can be fixed, but at least for a while it's probably a great
	idea not to save things that other versions won't load. */
```

It was just not deemed important enough to be fixed back when this code was written, I guess :)

**Comment by sagamusix** [comment]
The easy fix would be to just allow `ordnum` to be 257 but slurping at most `MAX_ORDERS` items when actually reading the order list, and skipping over the remaining bytes. Optimally the skipping code would verify that those extra items are actually `0xFF` and if they are not, present a warning.

**Comment by jpage8580** [comment]
Agreed. Loading should just check for MAX_ORDERS+1. Everything else would
then just stay the same.

**Comment by sagamusix** [comment]
Just to reiterate in case my suggestion wasn't clear, I don't think that this necessarily needs a special case for 257 orders. There is nothing inherently structurally broken if an IT file claims to contain, say, 439 orders (given that those order list items are actually present in the header). I think it would make more sense to ignore those extra patterns, show a warning in the loader but not outright reject the file because of that. The warning should obviously not be shown in case the extra items are just `---` patterns since this is legit in case of `ordnum == 257`.
