### ISSUE TITLE
Segfaults when loading it modules with some characters

### ISSUE THREAD

**Issue by gera2342** [schismtracker/schismtracker#481]
Commit after which segfaults occur: https://github.com/schismtracker/schismtracker/commit/b60172d48fa0f8ecef3f919992975a1a98b7e6fc

Example module: https://modarchive.org/index.php?request=view_by_moduleid&query=175919
Character "" (or \235) and maybe some others cause the crash.

**Comment by mrpapersonic** [comment]
Most likely its overflowing the song message buffer, which would explain the segfault anyway

**Comment by mrpapersonic** [comment]
Fixed with fcfb26019685a7d662ffc204ba6ef33c848b349a

**Comment by mrpapersonic** [comment]
That module contained an invalid character (namely 0x9D) which caused a chain reaction that led to the SDL conversion code dereferencing a NULL pointer; now schism just converts to a question mark if it sees an invalid character, which is really what it ought to do instead of showing a garbled mess.
