### ISSUE TITLE
Tremor (Ixx) effect timing wrong

### ISSUE THREAD

**Issue by izobilje** [schismtracker/schismtracker#489]
At least on my machine, tremor doesn't work as it used to. It is incosistent, sometimes off-rhythm, depending on tempo and sample length.

Like in this module: [test-tremor.zip](https://github.com/user-attachments/files/16141025/test-tremor.zip)

**Comment by sagamusix** [comment]
I cannot notice anything wrong here, or anything that used to work differently for that matter - even the oldest build I have lying around (2009-08-17) plays the file exactly like the latest release (2024-06-30) does.

Tremor is not executed if no sample is playing. That's why you get a strange rhythm on the first pattern and not on the second. But that is exactly what Impulse Tracker is doing as well. If you don't want that, you need to make sure that your sample is playing throughout the complete row, e.g. by setting loop points on the first sample.

Did I miss something or can you point out any differences where Schism Tracker's behaviour differs from Impulse Tracker's?

**Comment by izobilje** [comment]
1) What you said is right. The test case I first posted sounds the same in Impulse Tracker in DOSBox as in the newest Schism Tracker. Strange... it sounds inconsistent to me, but it is so.

2) However, I still think there is a change in tremor effect in recent versions of Schism. At least one of my modules which I made in older Schism Tracker sounds different, wrong, in new Schism Tracker and now I did some comparison between versions and found out the change appeared between 20230906 and 20231029.  

So here is another test case, that sounds OK in Impulse Tracker in DOSBox and Schism 20230906 but not later:
[test2-tremor.zip](https://github.com/user-attachments/files/16147278/test2-tremor.zip)

**Comment by mrpapersonic** [comment]
Looks to have broken in 2d564ba2. No idea why though, nothing looks broken at first glance

**Comment by mrpapersonic** [comment]
okay, tremor itself isn't broken, it's actually the combination of note cut and a tremor effect (`^^^.....I00`) that causes other tremors to overlap. It's likely due to the removal of the `chan->length = 0;` line, but I don't know if adding it back will break other things as well
