### ISSUE TITLE
Schism drops .xm effect E90

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#515]
E90 seems to disappear instead of being loaded as the nearest Qxy equivalent
![image](https://github.com/user-attachments/assets/7bbf9b20-a0a5-4cca-8c35-df9b0cdd4710)
![image](https://github.com/user-attachments/assets/ad631c88-fe00-4571-b03b-abc05e8e77dc)

Other 'normal' E9x values appear to convert just fine
![image](https://github.com/user-attachments/assets/11993abd-e5e0-4c0f-84a3-768e96aaecb7)
![image](https://github.com/user-attachments/assets/cc1e1842-061a-4d31-adde-db2016fbaa3c)

**Comment by sagamusix** [comment]
The reason why this command is not imported is because there is no clear mapping: `Q00` means "use previous effect parameter", but the implementation of `E90`  is buggy and simply retriggers the note once at the start of the row, so importing it as `Q00` would simply be wrong. It would have to be imported as `Q0x` with `x` being the current speed (and even that would just be an approximation of the XM behaviour), which is not known at the time the command is translated (and it cannot be known in the general case because a pattern may be played multiple times in a module at different speeds).

**Comment by 0xHexaDecimator** [comment]
If E90 retriggers the note once per row, then wouldn't the more accurate way of importing this be to simply enter it as a note (without effect) on those rows?

openMPT's way of handling this when changing module type from .xm --> .it is to enter Q00 in place of it, that seems to work well enough for them even if wrong.
![image](https://github.com/user-attachments/assets/9e1b053a-1c9b-4bd1-b637-18d4f857468a)
![image](https://github.com/user-attachments/assets/212718aa-efc2-4247-887b-626f22b6880f)

**Comment by mrpapersonic** [comment]
entering Q00 for E90 should be considered a bug in OpenMPT's conversion logic. I think putting nothing there on an E90 is acceptable behavior since there's no obvious way to convert it to IT and schism doesn't even promise full XM support anyway.

**Comment by sagamusix** [comment]
> the more accurate way of importing this be to simply enter it as a note (without effect) on those rows?

As said, the conversion process (both in Schism Tracker's XM import and OpenMPT's mod conversion) is not aware of the surrounding context; in particular that means that Schism Tracker has no idea what the last played note was so it cannot fill in that note.

**Comment by 0xHexaDecimator** [comment]
Fair

The only way it'd be fixed then is _yet another_ a compatibility effect, which at that point may also be able to tackle E9x values larger than the tick rate (another quirk of the effect). It'd also become a .mod compatibility effect at that point and not just .xm
But this is all incredibly uncommon, if a playback problem had negative priority, it'd be this one lol.
