### ISSUE TITLE
Doesn't sound right

### ISSUE THREAD

**Issue by SharkMachine** [schismtracker/schismtracker#525]
I don't know what is wrong, but this does not sound right

http://sharkma.ecxol.net/not-right.mkv

The version is what Ubuntu 24.04 offers.

**Comment by mrpapersonic** [comment]
That version is out of date and that bug was fixed months ago. Ubuntu managed to specifically pick up the worst of the playback bugs I caused :/. Someone ought to complain to the ubuntu package maintainers and get them to update it.

For now you can use the linux binary release or [build from source](https://github.com/schismtracker/schismtracker/raw/master/docs/building_on_linux.md) (it only takes about a minute to build the whole codebase)

**Comment by SharkMachine** [comment]
The binary doesn't work since `libFLAC.so.8: cannot open shared object file: No such file or directory`. I tried it before opening this issue.

I was able to build it, but immediately ran into #494. If I'm going to file a bug report to Launchpad, I'd rather ask them to update to a version that has neither of these bugs.

At least the playback is now correct and I only need to rename my files to get them to work.

**Comment by mrpapersonic** [comment]
That library is bundled with the binary. You can copy all the libraries in that folder to `/usr/local/lib` or preferably define `LD_LIBRARY_PATH=/path/to/schismtracker` before running schism.

**Comment by SharkMachine** [comment]
> That library is bundled with the binary. You can copy all the libraries in that folder to `/usr/local/lib` or preferably define `LD_LIBRARY_PATH=/path/to/schismtracker` before running schism.

Since I went the way to build it, it's irrelevant to me. I also prefer to do it this way instead of making changes to the system files.

Thanks for fixing #494. I've filed a report to Ubuntu to fix their package.
