### ISSUE TITLE
Use $HOME/.config to store user configuration files.

### ISSUE THREAD

**Issue by vdualb** [schismtracker/schismtracker#527]
Currently schism store config files in `$HOME` directory, but according to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/index.html) it should be stored in `$HOME/.config`. Also as a user I would like home directory be less polluted. Thanks

**Comment by mrpapersonic** [comment]
This is complicated, because just changing the directory would ruin people's existing configurations. I guess maybe the same thing that was suggested in #256 could be implemented but now defaulting to `~/.config` instead.

One thing to keep in mind is that Schism is very very old, and the XDG base directory specs were released only months before Storlek originally started working on loading and saving the config and fonts:
https://github.com/schismtracker/schismtracker/blob/0.04a/ChangeLog#L30-L38

Hence why that directory was chosen, simply because it *was* the general consensus standard for each program to have its own directory in `$HOME` at the time.
