### ISSUE TITLE
VF0 used to be treated as V80 but now no longer.

### ISSUE THREAD

**Issue by esaruoho** [schismtracker/schismtracker#531]
I have made a song with Schism Tracker ages ago.

I used `VF0` to set global volume to maximum.
Schism Tracker 20240909 now fully ignores it, and does not set it, because Schism has decided to only listen for `V80` to set maximum global volume, whereas originally it was anything over `V80` that was accepted as "set global volume".

<img width="133" alt="Screenshot 2024-09-30 at 11 25 03" src="https://github.com/user-attachments/assets/76996e1b-d33d-491d-ac4e-91fb426e340a">

meaning, in the screenshot, this should be a tiny duck of volume and back to maximum volume. instead `VF0` is ignored.

**Comment by sagamusix** [comment]
That behaviour is correct and hasn't changed since... forever basically. This line of code has sat there unchanged for at least 15 years: https://github.com/schismtracker/schismtracker/blame/3ed5b496013a645f026e4ffdb88e15a17c9bfa9b/player/effects.c#L1794

When you open the IT file, it tells which software version was used to save it. Can you share that information?

**Comment by esaruoho** [comment]
well good news, the song is from 2007.

**Comment by sagamusix** [comment]
We'll probably have to clamp Vxx parameters to V80 for Schism Tracker 0.50 and older then, no precise version information is available for those old versions.

**Comment by esaruoho** [comment]
ok the track that i had it on was 0.20
<img width="401" alt="Screenshot 2024-09-30 at 15 26 59" src="https://github.com/user-attachments/assets/8258a149-454a-42ea-aa8a-21533be3916c">

i hope that helps, @sagamusix 
i'm also seemingly using the trick on tracks made in 0.50

**Comment by mrpapersonic** [comment]
> We'll probably have to clamp Vxx parameters to V80 for Schism Tracker 0.50 and older then, no precise version information is available for those old versions.

I think this is the most sane solution (for now, anyway). I'm guessing this is also something ModPlug used to do as well, so we could apply it for those modules as well.

**Comment by sagamusix** [comment]
Yes, OpenMPT is already doing the same fix for modules saved with versions older than OpenMPT 1.17.03.02 (or 1.20 with compatible playback mode disabled).

The fix was introduced a few months before Schism switched to its current versioning scheme (in https://github.com/schismtracker/schismtracker/commit/ab5517d4730d4c717f7ebffb401445679bd30888), so all versions <= 0.50 need to be fixed.

**Comment by sagamusix** [comment]
There's probably quite a few other pattern commands that could use such a static fixup; OpenMPT's UpgradeModule.cpp has quite a few similar bugfixes for modules made with older (Open)MPT versions.
