### ISSUE TITLE
The X91 surround effect of XM modules is ineffective.

### ISSUE THREAD

**Issue by DroidU** [schismtracker/schismtracker#532]
If I open an XM file containing a surround (X91) effect edited with Modplug Tracker, that effect does not appear as S91 in the pattern editor, so it does not sound in surround. The same song is fine in OpenMPT and BeRoTracker.
Module needed to reproduce: `https://modland.com/pub/modules/Fasttracker%202/Ballistique/dots.xm`
The bug occurs on channel 12 of order 002.
Furthermore, Instrument 06 at the very beginning of the song sounds different than in the case of the above-mentioned 2 trackers.

**Comment by sagamusix** [comment]
X91 is a MPT extension, not strictly part of the XM format. Support can be added easily but that's why Schism does not support it.

> Furthermore, Instrument 06 at the very beginning of the song sounds different than in the case of the above-mentioned 2 trackers

IT is a single-format tracker. XM and IT envelopes may seem very similar on the surface but you will notice that if you convert the module to IT format in OpenMPT, the envelopes will sound strange there as well. To add insult to injury, this module actually exploits an old MPT bug regarding XM envelope handling, so Schism Tracker would actually not just have to implement XM-style envelope handling but it would have to support that MPT-specific quirk as well. That's not going to happen. XM support in Schism Tracker is always just a best-effort approach, you cannot expect perfect playback of this format. Please dont listen to XM files in Schism Tracker (and don't listen to to IT files in MilkyTracker).
