### ISSUE TITLE
missing version numbers in Schism Tracker 20241226 (MacOS)

### ISSUE THREAD

**Issue by suschizu** [schismtracker/schismtracker#585]
hello! the info.plist's CFBundleShortVersionString and CFBundleVersion keys are empty - so no version number shows up in the app:
<img width="273" alt="Screenshot 2024-12-26 at 20 51 14" src="https://github.com/user-attachments/assets/1a58f25e-e41b-4c03-bd17-3d7fc8e4baa8" />
<img width="417" alt="Screenshot 2024-12-26 at 20 52 18" src="https://github.com/user-attachments/assets/6bb59b68-b171-40a7-b23e-88a2742fe817" />

**Comment by mrpapersonic** [comment]
I changed the versioning to use the git date rather than the current date of the virtual machine (these are not the same because of timezones), it was such a trivial change that I didn't check if it worked lol. I'll fix it manually and reupload and find out what went wrong in the script

**Comment by suschizu** [comment]
great thanks for the quick fix! I can confirm that the version number shows up correctly :) cheers!
<img width="356" alt="Screenshot 2024-12-27 at 11 18 04" src="https://github.com/user-attachments/assets/db878052-b034-4914-8d15-05dd90122569" />

**Comment by p-linnane** [comment]
Hello! I'm a maintainer for the Homebrew package manager. Many downstreams, such as ourself, often consume releases shortly after they are pushed, since we automatically check upstream repositories. Force pushing tags that have already been publicly released ends up with situations such as https://github.com/Homebrew/homebrew-cask/pull/196684, where we find that the hash has changed for the tag. Often it's something simple like this, but it can be an indicator of malicious compromise of the upstream repo. The git manual has some good reading on this: https://git-scm.com/docs/git-tag#_on_re_tagging.

Naturally, you control your own project and can do as you please, but I wanted to bring some downstream perspective since this has happened a couple times with this project. Thank you!
