### ISSUE TITLE
UTF8 support

### ISSUE THREAD

**Issue by grivalera** [schismtracker/schismtracker#67]
I have Debian 7, successfully compilated project, but Russion chars (directory and filenames) are like hierogliphs, cann't used it caus of it.
I have UTF8 chars at filesystem.
How do I fix it? Maybe with compilation keys? 
![2017-02-01 23 10 57](https://cloud.githubusercontent.com/assets/25490736/22524302/bf345c24-e8d3-11e6-88a9-ddea56b9b40d.png)

**Comment by jangler** [comment]
Hm. Schism emulates a DOS program, so it uses code page 437 as its character encoding. Even if it correctly parsed UTF-8, it wouldn't have character graphics for all the Cyrillic, Greek, Japanese, Chinese, Arabic, Korean, etc. code points, since Schism uses its own built-in font.

It *might* be viable to implement a character encoding option supporting UTF-8 and at least draw �s for unrecognized characters. I'd have to look at the way text is handled internally.

**Comment by grivalera** [comment]
I can't get it, there are system monospace fonts available (Monospace, FreeMono, Liberation mono and so on) - is it possibel use it for UTF8 strings show?
Just use it for all unexpected chars, isn't it?

**Comment by jangler** [comment]
Yes, with SDL_ttf it would be possible to use a system default monospace font. It's just adding a new library dependency and a new drawing paradigm that might be tricky to implement, since nearly everything else in Schism (not just alphanumeric characters) is drawn in a text-mode sort of way using the current code page.

And it *would* have to be a config option, since there are no "unexpected" characters in the text encoding that Schism uses—check the Shift-F12 screen and this sample list art by Bogdan Raczynski:

![bogdan](https://cloud.githubusercontent.com/assets/1653421/22569449/92608c30-e965-11e6-9e2c-d5896c9f89fa.png)

All that aside, I agree that not supporting Unicode in 2017 is atavistic.

**Comment by 0x5742** [comment]
The reason for not supporting whatever font is because Schism Tracker's *entire interface* is using a specialized 8x8 font to begin with, and a lot of how it works depends on that fact. If you added a font library, you'd have to rewrite literally all of the UI and display code, on top of, well, requiring a font library. (Which isn't that tall of an order, but basically for the purposes of this thread, Schism Tracker is kind of a VGA emulator with a tracker attached to it)

Trying to add unicode support across the board would complicate the hell out of a lot of things, considering the way that the whole program is put together, but I think it'd be not too horribly difficult to add in a transliteration system to go from filesystem encoding to IT/CP437 just when reading filenames. Keep it localized to the directory scanning code in dmoz.c and save both the display- and filesystem-name of the loaded track.

You'd need to translate filenames differently for each OS so the filesystem-translit code would need to go into sys/win32/ and sys/posix/ (and maybe elsewhere?), and you'd still be restricted to what chars are available in CP437 (I really doubt anyone will want the IT high-bit chars in *filenames* so using the 437 high-bit set would make more sense) but it would be better than having "hieroglyphs" :)

**Comment by jangler** [comment]
Transliteration is a good idea.

**Comment by grivalera** [comment]
I think, that playing/editing files now has no troubles.
Now I see only troubles with browsing files.
May be use system dialog in special cases? Maybe make special keys for compiling/running Schism make it to use system browsing dialog?
I see it kind of "shishmtracker --sysdialogs" to make it available. As for me, tracker browsing dialog is not so important rather right files and directories names.
How to be with japaneese? China? German? Arabic? I think,all users with this language specifics will together say loud "thanks!" :-)

**Comment by HybridDog** [comment]
There's an imo more severe problem than the fonts: different keyboards aren't supported, temporarily changing the xkbmap is a dirty workaround.
Schismtracker uses an image as fonts (see shift+f12), and there are other styles which can be used. Adding Unicode support may break those styles.

**Comment by grivalera** [comment]
Ok. I got this, but I have troubles, why I shouldn't wait for it solving? I just offer several ways to do it, is it bad?

**Comment by vcaputo** [comment]
@grivalera the schism devs seem pretty receptive to contributions, AKA PRs welcome!

**Comment by jangler** [comment]
#68 is related to the keyboard issue Hybrid mentioned. I got started working on it some time ago and then got distracted by other things…

There's actually a bunch of (unfinished? unimplemented?) code regarding keyboard remapping, but that's all beside the point of this thread.

I like the idea of a `--sysdialogs` flag or config option, but it again requires adding another library dependency. There actually isn't one single "system browsing dialog" either; the details depend on what GUI toolkit you're using. Tk would probably be the most sane choice if we were to follow that path.

**Comment by grivalera** [comment]
I know, there are some X-dialogs are in Linux, and other guys using the same way: they just uses compilation keys for user-specific libraries (KDE, GDM and so on).

**Comment by ElectricKeet** [comment]
Starting with the disclaimer that regardless of how much technical knowledge I may have, I am most certainly _not_ a coder...

The "Notes" screen is switchable between the loaded interface font and the system (OEM) font. Can that mechanism be used to modify all the other places that display filenames, sample names, and all that? Force them to use the system font mode for the texty bits, and then patch that to send those to essentially a second rendering pass that's Unicode-friendly and uses a vector font library?

(As an aside, even if everything stays as it is as far as the character set and raster rendering, there's a part of me that would be happy if we could replace the 8×8 cells with something a bit more modern, like 64×64 or something, 'cause then I'd get another excuse to whip up some new bitmap fonts with a bit more flexibility. But, you know, I'm a font nerd.)

**Comment by HybridDog** [comment]
What is the "Notes" screen?

You could replace the 8x8 pixel fonts with monospace truetype fonts in text areas.
The 8x8 fonts are not abolished but they're not longer used as fonts but only as images (press shift+F12 to see them). So when displaying readable text, the truetype font is used and when displaying sliders etc. the 8x8 font images are used. Displaying the played samples also should keep using the 8x8 fonts because l like how it looks:
![2017-08-26-093355_1920x1056_scrot](https://user-images.githubusercontent.com/3192173/29739599-e8751ef6-8a41-11e7-8e1f-ce951c73e26f.png)

**Comment by ElectricKeet** [comment]
By "Notes" I meant the "Message Editor". You know, the big box for typing in song descriptions and greets and such? I always forget what it's called (and the key combination to get to it, because I'm like that.)

That's exactly what I had in mind, anyhow. The tricky part is getting arbitrary vector fonts to display nicely in a grid like that. OpenMPT manages, but it renders then as one-bit aliased type. DefleMask (a tracker for early game console FM- and PSG-type hardware) uses OpenGL to lay everything out, but it was built with that from the start (and using an absolutely dreadful library, too.)

If someone wants to take up "trick Schism into using much higher resolution tiles for interface rendering" as a personal project, I'm keen to assist as I can, but that should probably be its own separate issue/thread.

If we're still focussing on support for other 8-bit codepages, I can retrofit some of the more popular fonts for those, at least.

**Comment by HybridDog** [comment]
The Pixel letters aren't ASCII, so extending them to utf is not a good idea l think. You could make a converter which creates a ttf font from a schismtracker font.

How do you switch to system font in message editor (shift+F9)?
And what does extended ASCII mode do?

**Comment by jangler** [comment]
Extended ASCII is a type of character encoding that uses the unused bit of ASCII to add another 128 characters to the set. I believe Schism Tracker specifically uses code page 437 for its extended ASCII. I'm not actually sure what Ctrl-T does in this instance though besides change the text color, since I can enter things like Σ regardless of the state of that toggle.

To be clear, the "OEM font" in Schism Tracker is purely emulated and has nothing to do with the actual system that Schism is running on. It still uses the same drawing procedure as the rest of the interface.

I still think transliteration is probably the best idea. Is transliteration from cyrillic to latin regular?

**Comment by grivalera** [comment]
Transliteration table (russian letters to english) easy to implement and regular, you are right.
It seems more like crutch to me and my answer :-)
Last time I just copied all files to english-letterred dirs, and trouble disappeared.

**Comment by HybridDog** [comment]
Transliteration doesn't work for Chinese characters, does it?

**Comment by jangler** [comment]
No. It would be easy for Japanese hiragana and katakana, and Korean hangul, but not for Chinese characters, since they have multiple readings.

**Comment by grivalera** [comment]
I can't get. Does schism use inside 8-bit chars or full-length chars? Is it possible make convertation (transliteration) on-a-fly? It needs to make convertation table once, and its enough. In case of non-8-bits internal chars, of course. Or, just translate all letters from source 8-bit type (its only inside the module choosen to load, usually not in the system!) to extended 16-bit format, and use of all dialogs will haven't troubles because of it. And our chineese and japanian friends can just participate and draw useful symbols and append convertation data. Is it real?
Ok, it needs to be drawn only first 256 letters (from original DOS-symbols table), all other might be got from monospaced system symbolsets. Is it solution?

**Comment by HybridDog** [comment]
> Ok, it needs to be drawn only first 256 letters (from original DOS-symbols table), all other might be got from monospaced system symbolsets. Is it solution?

l assume it's a lot easier to use monospaced system ttf for specific things, e.g. file names and paths and the current 8 Bit schismtracker font for the other text.

**Comment by HybridDog** [comment]
I think for transliteration you could convert a Utf8 character to one or more schismtracker font character.
The file path is coded in Utf8 and needs to be shown in schismtracker. You could e.g. change the newline character to \n.
Here're a few Unicode characters which directly represent a character in schismtracker font: 
```
d ☺ ☻ ♥ ♦ ♔ ♕ t t t t ♂ ♀ t ♬ ☼
t t t t ¶ § t t ↑ ↓ → ← t ↔ t t
d d d d d d d d d d d d d d d d
d d d d d d d d d d d d d d d d
d d d d d d d d d d d d d d d d
d d d d d d d d d d d d d d d d
d d d d d d d d d d d d d d d d
d d d d d d d d d d d d d d d t
t t t t t t t t t t t t t t t t
t t t t t t t t t t t t t t t t
t t t t t t t t t t t t t t t t
t t t t t t t t t t t t t t t t
t t t t t t t t t t t t t t t t
t t t t t t t t t t t t t t t t
α β t π ∑ σ µ t t ϴ Ω t ∞ t ∈ t
≡ ± t t t t ÷ ≈ ° · t √ t ² t t

d: both are same
t: to do
```
![2017-10-11-104945_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/31432147-17495ce4-ae76-11e7-9738-76bb51c28e4e.png)

**Comment by grivalera** [comment]
Can't get it. What does mean this table? How to connect "d d t t"-table with symbols under?

**Comment by grivalera** [comment]
Do you invite me to draw? I happy to participate!

**Comment by HybridDog** [comment]
The table shows 256 Utf8 characters which look like the characters in schismtracker. d means the value of the Utf8 character and the schismtracker character are the same, e.g. the readable ASCII letters. t means that I haven't yet found an Utf8 character which looks like the schismtracker character.
Anyway, a mapping from Utf8 to schismtracker is more important than the other way round.
The newline ASCII character e.g. could be mapped to two schismtracker characters in file paths: `\n`.

**Comment by alexmyczko** [comment]
@grivalera you know you can start it with this option? schismtracker --font-editor

**Comment by trebmuh** [comment]
(_reproducing #184 here_)

In this image (where I removed some folder names for a better understanding), I have 3 directories with French accents : "Modèles", "Téléchargements", and "Vidéos", but the accentuated characters are wrongly displayed:

![schism-caracteres-bizarres](https://user-images.githubusercontent.com/8705846/50388633-be9dc480-071c-11e9-83e0-a3f6b288eec3.png)

**Comment by jesus2099** [comment]
Schism is a way to continue using Impulse Tracker 2.
Impulse Tracker 2 was in a fixed codepage and that did not prevent us from creating or playing music or writing our silly sample/instrument texts.
I think it's always important to be fully Unicode compliant for everything but, honestly, for an Impulse Tracker 2 clone, it is really not required and it would deviate from IT2. 
Not only it would require lot of dev works that would be needed on other issues but it would generate incompatible IT files in the end.

I also see glitches instead of accentuated characters, but it does not prevent me from doing what's most important.

**Comment by mrpapersonic** [comment]
This should now be handled with 1f10ee72191176dedcf4e98137f2a3a57d07f3ff. any character that can't be displayed in the vga bios font Schism comes with will be rendered as a `?`
