### ISSUE TITLE
OpenGL video mode segfaults

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#71]
Might be some dumb Linux thing. I don't remember this happening just after our last change to the video code.

**Comment by jangler** [comment]
Anyone else have this problem?

**Comment by HybridDog** [comment]
l use opengl mode and have never run into such crashes.

**Comment by alugarius** [comment]
No problems on my Debian9 64bit

**Comment by jangler** [comment]
I guess I'll leave this open until some update fixes it on my system… works fine on Debian sid in crouton, too.

**Comment by vcaputo** [comment]
also unreproducible here on debian 8 x86_64

**Comment by alugarius** [comment]
Checked on Debian 8 
Works

**Comment by jangler** [comment]
Sadly still broken for me. Wonder what's different about my Arch system that causes this problem.

**Comment by vcaputo** [comment]
@HybridDog may have reproduced this in an unrelated issue judging from his valgrind output: https://github.com/schismtracker/schismtracker/issues/90#issuecomment-309237262

**Comment by HybridDog** [comment]
jangler, does this happen when resize is called with width=0 and height=0?
https://github.com/schismtracker/schismtracker/blob/master/schism/video.c#L851
https://github.com/schismtracker/schismtracker/blob/master/schism/video.c#L442
https://github.com/schismtracker/schismtracker/blob/master/schism/video.c#L1160
maybe it has to do with texsize: https://github.com/schismtracker/schismtracker/blob/master/schism/video.c#L1119

**Comment by HybridDog** [comment]
l somehow managed to make it keep aspect ratio when changing window size.
![2017-08-09-142634_795x712_scrot](https://user-images.githubusercontent.com/3192173/29121479-ee2d5ce0-7d0e-11e7-927b-5fe9a333cd17.png)
I don't know how l did it and l can't find where in the settings it's configured this way.
Setting want_fixed to 1 does nothing.

**Comment by jangler** [comment]
Uhmmm interesting. I have not seen this and have no idea why it would happen. IIRC `want_fixed` only has to do with fullscreen.

**Comment by HybridDog** [comment]
l noticed that it doesn't keep aspect ratio since l recompiled. And now l don't know how to archive this problem again.

Anyway, valgrind shows lots of error messages in opengl mode.

**Comment by abandpass** [comment]
When i compiled schism tracker 20170910 on my computer under Linux, i had trouble getting open gl to work too.

I was getting this kind of error message :
libGL error: No matching fbConfigs or visuals found                                                                                                                         
libGL error: failed to load driver: swrast                                                                                                                                  
X Error of failed request:  BadValue (integer parameter out of range for operation)                                                                                         
  Major opcode of failed request:  154 (GLX)                                                                                                                                
  Minor opcode of failed request:  3 (X_GLXCreateContext)                                                                                                                   
  Value in failed request:  0x0                                                                                                                                             
  Serial number of failed request:  32                                                                                                                                      
  Current serial number in output stream:  33                                                                                                                               
Segmentation fault (core dumped)        

I don't know why my other OpenGL software worked like Blender, FreeCAD or my steam games.

I fixed this problem with the following commands:
cd /usr/lib/x86_64-linux-gnu/mesa/
sudo mv libGL.so.1.2.0 libGL.so.1.2.0.bak
sudo ln -s /usr/lib/nvidia-384/libGL.so.1 libGL.so.1.2.0

The OpenGL lib now points to a hardware accelerated one for my Nvidia video card.

Disclaimer : i don't really know what i'm doing.

**Comment by jangler** [comment]
Yeah, I still get a segfault when I try to switch to OpenGL mode. I have the proprietary Nvidia drivers for GLX.

**Comment by HybridDog** [comment]
It doesn't happen on intel and amd graphics.
Maybe you can do that: https://davidgow.net/musings/nvidia-opengl-debug-output.html
Using that: https://github.com/apitrace/apitrace

Edit: It doesn't happen to me.

**Comment by jangler** [comment]
In Feb 2017 (when this issue was first posted) I had integrated Intel graphics, though.

**Comment by royalsefton** [comment]
Issue currently exists for me in Pop!_OS 20.04 amd64
Linux kernel 5.4.0-7634-generic
Nvidia proprietary driver 440.100
RTX 2070 Max-Q (laptop GPU)
Workaround: use Intel or Hybrid (Prime offloading) graphics so schismtracker starts with Intel acceleration rather than Nvidia acceleration. Not fond of doing this right now as I cannot connect to external displays in Intel or Hybrid modes on this laptop.

Tried apitrace, going into Ctrl F1 screen, selecting OpenGL Display. Please advise if more debug output is needed; I couldn't understand how to enable Nvidia driver debugging based on the above link.

apitrace: loaded into /usr/bin/apitrace
apitrace: unloaded from /usr/bin/apitrace
apitrace: loaded into /usr/local/bin/schismtracker
apitrace: redirecting dlopen("libGL.so", 0x102) from /lib/x86_64-linux-gnu/libSDL-1.2.so.0
apitrace: tracing to /home/royalsefton/.schism/schismtracker.trace
apitrace: attempting to read configuration file: /home/royalsefton/.config/apitrace/gltrace.conf
apitrace: warning: unknown function "wglAllocateMemoryNV"
apitrace: warning: unknown function "wglFreeMemoryNV"
apitrace: warning: caught signal 11
apitrace: flushing trace
/usr/bin/../lib/x86_64-linux-gnu/apitrace/wrappers/glxtrace.so+0x1e1c99
/lib/x86_64-linux-gnu/libc.so.6+0x4620f
schismtracker: vgamem_scan32+0x4518f: ../include/vgamem-scanner.h:34
schismtracker: _blit11+0x5264b: ../schism/video.c:1599
schismtracker: video_blit+0x5490b: ../schism/video.c:1742
schismtracker: event_loop+0x526: ../schism/main.c:937
schismtracker: main+0x526: ../schism/main.c:1158
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main+0xf2
schismtracker+0xffed
?
apitrace: info: taking default action for signal 11

**Comment by jangler** [comment]
Resolved by 869c01e.
