### ISSUE TITLE
I want to donate over paypal

### ISSUE THREAD

**Issue by alugarius** [schismtracker/schismtracker#72]

**Comment by jangler** [comment]
@Storlek, do you take straight-up PayPal? I know you have [a Patreon](https://www.patreon.com/Storlek).

**Comment by jangler** [comment]
(Also thank you!)

**Comment by alugarius** [comment]
are you one of the main developer?

Also id like to see some things: 
Is SDL2 support planned and is it possible to make an static build?

**Comment by alugarius** [comment]
Patreon is a little useless for me becouse i cant pay monthly, but id like so donate about 20€ over paypal

**Comment by jangler** [comment]
I'm currently one of the main developers, but Storlek has put far more work into Schism than I have. (And I feel the same way you do about Patreon.)

Although SDL2 support is definitely something we'd like to have for several reasons, I'm mainly just focused on fixing bugs and implementing small features, so I do not personally plan to do a SDL2 rewrite unless platforms like OS X stop supporting SDL1.2. @davvid did some work porting Schism to SDL2 a while ago, but I'm not sure what the status of that is now.

I imagine a static build would be possible, but I've never looked into it (partly because I am not well versed in the GNU autotools). Trying to remember if this has been discussed before…

**Comment by 0x5742** [comment]
If you want to get money to me, Patreon is the way to go. Anything else (eg PayPal) ends up being a hassle and will eat up money in various fees.

I've got Square, but that only works for USD.

You could back me, wait for payment to hit, and then like, unsubscribe?

**Comment by jangler** [comment]
Wouldn't have expected a donation offer to be a "wontfix" :P

**Comment by alugarius** [comment]
I have current problems with patreon, I will try that if I got my accounts fixes,

 @jangler, with that SDL thing I recommend to port to SDL2 like MilkyTracker did with there first 1.x version (congrats to them) because SDL1 is not supporting new WMs and systems like Wayland.
Sure Xwayland could help, but then I am close to emulate old piece of software. ..and then I just could use DosBox with the Impulsetracker

**Comment by alugarius** [comment]
i am a patreon on a unspecified time now, closing this issue

**Comment by 0x5742** [comment]
I'm a bit late on the reply here, but thank you :)
