### ISSUE TITLE
SDL2 port (Wayland/Mir)

### ISSUE THREAD

**Issue by alugarius** [schismtracker/schismtracker#73]
Schism schould go on SDL2 (this year?).
MilkyTracker1.0 (my current main tracking software) also realized that its time.

We shouldn't wait until systems stop supporting SDL1, SDL 1 already stopped (or never did) supporting some systems that are/will be in use soon.
SDL1 is legacy supported, that means that's only for giving software the time to port to the new version.

Better be prepared.

**Comment by jangler** [comment]
SDL1.2 is hardly even legacy supported anymore; I agree that SDL2 is the way forward. Since we haven't heard from davvid (not going to tag again) on their SDL2 porting effort in quite a while, I think I need to go look into approximately what would need to be changed. I suspect this may mean I'll have to actually understand the drawing code…

**Comment by alugarius** [comment]
Any progress here

**Comment by jangler** [comment]
No, but maybe this should be the next priority after tackling the remaining issues with MIDI and automatic deployment.

**Comment by jangler** [comment]
I'm going to close this issue since #33 already addresses it.
