### ISSUE TITLE
Many MIDI drivers do not support proper polling

### ISSUE THREAD

**Issue by vcaputo** [schismtracker/schismtracker#98]
If you change TiMidity++ settings and restart it without exiting schism, while schism is configured with output to TiMidity++, that MIDI port in schism gets into a bad state and you can't reset it by going to the MIDI configuration page and cycling through its Output->Disabled->Output options; they refuse to change.

**Comment by jangler** [comment]
IMO the MIDI Screen should refresh whenever you view it anyway.

**Comment by mrpapersonic** [comment]
The root problem of the issue is that the alsa code doesn't handle refreshing *at all*:
https://github.com/schismtracker/schismtracker/blob/bec30a07f806c6f28e9791807d6868d219956755/sys/alsa/midi-alsa.c#L383

Under the jack driver (which does), this problem doesn't exist as the midi port will eventually go away anyway
